addons:
- name: gng-nginx
  versions:
    start: ""
    end: ""
  notes: ""
  source:
    chart: ingress-nginx
    repository: https://kubernetes.github.io/ingress-nginx
  warnings:
  - 'Prior to upgrading, you must delete the following Kubernetes jobs to avoid upgrade
    and deployment failures:'
  - ingress-nginx-admission-create
  - ingress-nginx-admission-patch
  compatible_k8s_versions:
    min: ""
    max: ""
  necessary_api_versions: []
  values_schema: |
    {
    "$schema": "http://json-schema.org/schema#",
    "type": "object",
    "properties": {
      "image": {
        "type": "object",
        "required": [
          "repository",
          "pullPolicy"
          ],
          "properties": {
            "repository": {
              "type": "string",
              "pattern": "^[a-z0-9]+"
            },
            "pullPolicy": {
              "type": "string",
              "pattern": "pizza"
            }
          }
        }
      }
    }
  opa_checks:
  - |
    package Fairwinds ingressesWithoutHttpPaths[actionItem] {
            input.kind == "Ingress"
            rule := input.spec.rules[_]
            not rule.http.paths
            actionItem := {
              "title": "HTTP Path Not Present",
              "description": "A bug in version 2.5.0 makes it unable to handle ingress rules without an http path",
              "severity": 0.1,
              "remediation": "Upgrade to at least patch version v2.5.1 of the app, chart version 1.5.2. See https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases/tag/v2.5.0 for details",
              "category": "Reliability"
            }
          }
  resources:
  - networking.k8s.io/v1/ingresses
