project_name: gonogo
release:
  prerelease: auto
  github:
    owner: FairwindsOps
    name: gonogo
builds:
  - id: gonogo
    binary: gonogo
    ldflags:
      - -X main.version={{.Version}} -X main.commit={{.Commit}} -s -w
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

signs:
- cmd: cosign
  args: ["sign-blob", "--key=hashivault://cosign", "-output-signature=${signature}", "${artifact}"]
  artifacts: checksum

docker_signs:
- artifacts: all
  args: ["sign", "--key=hashivault://cosign", "${artifact}", "-r"]

brews:
  - name: gonogo
    goarm: 6
    tap:
      owner: FairwindsOps
      name: homebrew-tap
    folder: Formula
    description: Check cluster addons for upgrade confidence
    test: |
      system "#{bin}/gonogo version"


dockers:
- image_templates:
  - "us-docker.pkg.dev/fairwinds-ops/oss/gonogo:{{ .Tag }}-amd64"
  - "us-docker.pkg.dev/fairwinds-ops/oss/gonogo:v{{ .Major }}-amd64"
  - "us-docker.pkg.dev/fairwinds-ops/oss/gonogo:v{{ .Major }}.{{ .Minor }}-amd64"
  dockerfile: Dockerfile
  build_flag_templates:
  - "--platform=linux/amd64"
- image_templates:
  - "us-docker.pkg.dev/fairwinds-ops/oss/gonogo:{{ .Tag }}-arm64v8"
  - "us-docker.pkg.dev/fairwinds-ops/oss/gonogo:v{{ .Major }}-arm64v8"
  - "us-docker.pkg.dev/fairwinds-ops/oss/gonogo:v{{ .Major }}.{{ .Minor }}-arm64v8"
  goarch: arm64
  dockerfile: Dockerfile
  build_flag_templates:
  - "--platform=linux/arm64/v8"
- image_templates:
  - "us-docker.pkg.dev/fairwinds-ops/oss/gonogo:{{ .Tag }}-armv7"
  - "us-docker.pkg.dev/fairwinds-ops/oss/gonogo:v{{ .Major }}-armv7"
  - "us-docker.pkg.dev/fairwinds-ops/oss/gonogo:v{{ .Major }}.{{ .Minor }}-armv7"
  goarch: arm64
  dockerfile: Dockerfile
  build_flag_templates:
  - "--platform=linux/arm/v7"
docker_manifests:
- name_template: us-docker.pkg.dev/fairwinds-ops/oss/gonogo:{{ .Tag }}
  image_templates:
  - "us-docker.pkg.dev/fairwinds-ops/oss/gonogo:{{ .Tag }}-amd64"
  - "us-docker.pkg.dev/fairwinds-ops/oss/gonogo:{{ .Tag }}-arm64v8"
  - "us-docker.pkg.dev/fairwinds-ops/oss/gonogo:{{ .Tag }}-armv7"
- name_template: us-docker.pkg.dev/fairwinds-ops/oss/gonogo:v{{ .Major }}
  image_templates:
  - "us-docker.pkg.dev/fairwinds-ops/oss/gonogo:v{{ .Major }}-amd64"
  - "us-docker.pkg.dev/fairwinds-ops/oss/gonogo:v{{ .Major }}-arm64v8"
  - "us-docker.pkg.dev/fairwinds-ops/oss/gonogo:v{{ .Major }}-armv7"
- name_template: us-docker.pkg.dev/fairwinds-ops/oss/gonogo:v{{ .Major }}.{{ .Minor }}
  image_templates:
  - "us-docker.pkg.dev/fairwinds-ops/oss/gonogo:v{{ .Major }}.{{ .Minor }}-amd64"
  - "us-docker.pkg.dev/fairwinds-ops/oss/gonogo:v{{ .Major }}.{{ .Minor }}-arm64v8"
  - "us-docker.pkg.dev/fairwinds-ops/oss/gonogo:v{{ .Major }}.{{ .Minor }}-armv7"