version: 2.1

orbs:
  orb-tools: circleci/orb-tools@10.1.0
  rok8s: fairwinds/rok8s-scripts@11
  oss-docs: fairwinds/oss-docs@0



jobs:
  publish_docs:
    docker:
      - image: cimg/node:15.5.1
    steps:
      - checkout
      - run:
          name: Build Docs Site
          command: |
            set -e
            cd ./docs
            npm install
            npm run check-links
            npm run build
      - run:
          name: Install AWS CLI
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
      - run:
          name: Publish Docs Site to S3
          command: |
            cd ./dist
            aws s3 sync ./ s3://gonogo.docs.fairwinds.com --delete
workflows:
  version: 2
  release:
    jobs:
      - publish_docs:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/